kyan/jukebox-js

backend/package.json
backend/test/routes.test.js
backend/yarn.lock
frontend/yarn.lock

Upgraded a couple of npm and started looking at the specs in backend

npm upgrades

---

backend/src/lib/transformer/index.js
frontend/src/actions/index.js
frontend/src/actions/index.spec.js
frontend/src/components/volume-buttons/__snapshots__/index.spec.js.snap
frontend/src/components/volume-buttons/index.js
frontend/src/components/volume-buttons/index.spec.js
frontend/src/constants/index.js
frontend/src/constants/mopidy-api.js
frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
frontend/src/containers/dashboard/index.js
frontend/src/containers/dashboard/index.spec.js
frontend/src/containers/jukebox-middleware/index.js
frontend/src/containers/jukebox-middleware/index.spec.js
frontend/src/reducers/jukebox/index.js
frontend/src/reducers/jukebox/index.spec.js
frontend/src/utils/on-message-handler/index.js
frontend/src/utils/on-message-handler/index.spec.js

Adds volume control, including syncing.
https://github.com/kyan/jukebox-js/issues/7

#7 Add volume control

---

frontend/src/actions/index.js
frontend/src/actions/index.spec.js
frontend/src/constants/mopidy-api.js
frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
frontend/src/containers/dashboard/index.js
frontend/src/containers/dashboard/index.spec.js

Added skip forward and back buttons

---

backend/package.json
backend/src/app.js
backend/src/lib/broadcaster/index.js
backend/src/lib/broadcaster/index.spec.js
backend/src/lib/message-handler/index.js
backend/src/lib/message-handler/index.spec.js
backend/src/lib/str-to-function/index.spec.js
backend/src/lib/transform-track/index.spec.js
backend/src/lib/transformer/index.spec.js
backend/test/routes.test.js
backend/yarn.lock
frontend/src/components/tracklist/__snapshots__/index.spec.js.snap
frontend/src/components/tracklist/index.css
frontend/src/components/tracklist/index.js
frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
frontend/src/utils/on-message-handler/index.js
frontend/yarn.lock

100% coverage for the backend 👍

backend specs now 100%!

---

frontend/README.md
frontend/package.json
frontend/src/App.js
frontend/src/actions/index.js
frontend/src/app.spec.js
frontend/src/components/current-track/index.js
frontend/src/components/current-track/index.spec.js
frontend/src/components/skip-buttons/index.js
frontend/src/components/tracklist/index.js
frontend/src/components/url-drop-area/index.js
frontend/src/components/url-drop-area/index.spec.js
frontend/src/components/volume-buttons/index.js
frontend/src/constants/index.js
frontend/src/containers/current-track-container/index.js
frontend/src/containers/current-track-container/index.spec.js
frontend/src/containers/dashboard/index.js
frontend/src/containers/dashboard/index.spec.js
frontend/src/containers/jukebox-middleware/index.js
frontend/src/containers/jukebox-middleware/index.spec.js
frontend/src/index.js
frontend/src/reducers/track/index.spec.js
frontend/src/reducers/tracklist/index.spec.js
frontend/src/selectors/index.js
frontend/src/setupTests.js
frontend/src/utils/images/index.js
frontend/src/utils/on-message-handler/index.spec.js
frontend/src/utils/time/index.js
frontend/yarn.lock

Add standard JS for linting and code style

---

README.md
backend/README.md
frontend/README.md

Start adding some documentation

---

backend/README.md
backend/package.json
backend/src/app.js
backend/src/lib/broadcaster/index.js
backend/src/lib/message-handler/index.js
backend/src/lib/message-handler/index.spec.js
backend/src/lib/payload/index.js
backend/src/lib/payload/index.spec.js
backend/src/lib/str-to-function/index.js
backend/yarn.lock
frontend/src/constants/mopidy-api.js
frontend/src/containers/jukebox-middleware/index.js
frontend/src/containers/jukebox-middleware/index.spec.js
frontend/src/utils/on-message-handler/index.js
frontend/src/utils/payload/index.js
frontend/src/utils/payload/index.spec.js

Payload normalisation

---

backend/README.md
backend/package.json
backend/shipitfile.js
backend/yarn.lock

Starting to get stuff deployable

---

frontend/package.json
frontend/src/App.js
frontend/src/__snapshots__/app.spec.js.snap
frontend/src/actions/index.js
frontend/src/actions/index.spec.js
frontend/src/components/clear-playlist/__snapshots__/index.spec.js.snap
frontend/src/components/clear-playlist/index.js
frontend/src/components/controls/index.js
frontend/src/components/current-track/__snapshots__/index.spec.js.snap
frontend/src/components/current-track/index.js
frontend/src/components/skip-buttons/index.js
frontend/src/components/skip-buttons/index.spec.js
frontend/src/constants/index.js
frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
frontend/src/containers/dashboard/index.js
frontend/src/containers/dashboard/index.spec.js
frontend/src/containers/settings/__snapshots__/index.spec.js.snap
frontend/src/containers/settings/index.js
frontend/src/containers/settings/index.spec.js
frontend/src/reducers/index.js
frontend/src/reducers/settings/index.js
frontend/src/reducers/settings/index.spec.js
frontend/yarn.lock

Adds some local storage for settings and the beginnings of a settings interface. Plus some other refactoring and UI updates.

Persistence

---

README.md
backend/jukebox-api.service
backend/package.json
backend/shipitfile.js
frontend/package.json

Updating production deployment information.

Deployment changes

---

README.md
backend/shipitfile.js
backend/src/lib/services/mopidy/index.js
frontend/package-lock.json
frontend/package.json
frontend/src/__snapshots__/app.spec.js.snap
frontend/src/containers/dashboard/__snapshots__/index.spec.js.snap
frontend/src/containers/dashboard/index.js
frontend/src/containers/dashboard/index.spec.js

Refactored the large `<Dashboard>` component to use `Hooks`. Unfortunately Enzyme does not appear ready for hooks yet so I couldn't get 100% coverage! I wonder if a later PR should be done to switch to https://github.com/testing-library/react-testing-library which seems to be referenced more in the React and Redux docs.

 Bit of an exercise in using some of the new React Hooks

---

backend/package.json
backend/src/lib/constants/settings.js
backend/src/lib/local-storage/index.js
backend/src/lib/services/mopidy/tracklist-trimmer/index.js
backend/src/lib/services/mopidy/tracklist-trimmer/index.spec.js
backend/src/lib/services/spotify/index.js
backend/src/lib/services/spotify/index.spec.js
backend/src/lib/transformer/index.js
backend/src/lib/transformer/index.spec.js
docker-compose.yml

Some more additions to the suggestions work so I can get something up and running to soak test. Could probably do with more specs but that's always the case.

Adding track trimmer and tweak suggestions

---

backend/src/lib/transformer/index.js

When a track is removed we need to clear the suggestion setinterval

quick fix for clearing recomenderator

---

backend/src/lib/services/spotify/index.js
backend/src/lib/transformer/index.js

Stops the playlist growing bigger and bigger over night. Made some tweaks to recommendations too just to see what happens.

Fixes dupe recommendations being made which broke the tracklist

---

.env.example
scripts/deploy-client.sh

Fixes issue where the CLIENT_ID was being set the same for production and dev

Fix for client ID in production

---

backend/package-lock.json
backend/package.json
backend/src/app.js
backend/src/lib/scheduler/index.js
backend/src/lib/scheduler/index.spec.js

This PR
* Adds the `node-cron` package to the jukebox for scheduling
* On server start it sets up one job to stop the JB at 7pm

Auto stop the jukebox

---

backend/src/app.js
backend/src/lib/services/mopidy/index.js
backend/src/lib/services/mopidy/index.spec.js
frontend/package.json
frontend/src/components/current-track/__snapshots__/index.spec.js.snap
frontend/src/components/current-track/index.css
frontend/src/components/current-track/index.js
frontend/src/containers/current-track-container/index.js
frontend/src/containers/jukebox-middleware/index.js
frontend/src/containers/jukebox-middleware/index.spec.js
frontend/src/reducers/assets/index.js
frontend/src/reducers/timer/index.js
frontend/src/reducers/timer/index.spec.js
frontend/src/utils/time/index.js

Add track time remaining information and refactor some of the messaging code.

Time remaining and code cleanup

---

backend/package.json
backend/src/handlers/authenticate/index.js
backend/src/handlers/mopidy/index.js
backend/src/services/mongodb/models/user/index.js
backend/src/services/mopidy/index.js
backend/src/services/mopidy/index.spec.js
backend/src/services/spotify/index.js
backend/src/services/spotify/index.spec.js
backend/src/utils/broadcaster/index.js
backend/src/utils/broadcaster/index.spec.js
backend/src/utils/track/index.js
backend/src/utils/track/index.spec.js
backend/src/utils/transformer/index.js
backend/src/utils/transformer/index.spec.js
backend/src/utils/transformer/transformers/mopidy/track/index.spec.js
backend/src/utils/transformer/transformers/mopidy/tracklist/index.js
backend/src/utils/transformer/transformers/mopidy/tracklist/index.spec.js
frontend/src/components/tracklist/added-by/__snapshots__/index.spec.js.snap
frontend/src/components/tracklist/added-by/index.js
frontend/src/components/tracklist/added-by/index.spec.js
frontend/src/components/tracklist/index.css
frontend/src/constants/mopidy-api.js

Various tweaks to AddedBy UI and also moving it inside the Transformer.

Some tweaks to addedBy

---

backend/src/services/spotify/index.js
backend/src/services/spotify/index.spec.js
backend/src/utils/track/index.js
backend/src/utils/track/index.spec.js
backend/src/utils/transformer/index.js

Also converted `addTrack` to `addTracks` for future use as well as getting it to return a promise.

Make sure we add the tracks in mongo first

---

backend/src/services/spotify/index.js
backend/src/services/spotify/index.spec.js

Use ImageCache when image data available

---

backend/src/decorators/mopidy/index.js
backend/src/decorators/mopidy/index.spec.js
backend/src/services/mopidy/tracklist-trimmer/index.js
backend/src/services/spotify/index.js
backend/src/utils/recommendations/index.js
backend/src/utils/recommendations/index.spec.js

This selects 3 random tracks as a fallback for when recommendations returns nothing.
closes #137

Improve recommendation fallback

---

frontend/src/components/tracklist/__snapshots__/index.spec.js.snap
frontend/src/components/tracklist/index.css
frontend/src/components/tracklist/index.js
frontend/src/containers/dashboard-container/__snapshots__/index.spec.js.snap

Improve tracklist making it easier to see stuff

---

backend/src/app.js
backend/src/services/mongodb/index.js
backend/src/services/mongodb/index.spec.js
backend/src/services/mopidy/index.js
frontend/src/components/volume-buttons/index.js
frontend/src/components/volume-buttons/index.spec.js

Promisify some of the main connections the API makes rather than use callbacks. I have also added the vol up/down increment and along with a config change will try and improve the volume. I actually think fixing it will require a proper soundcard in maybe a mini PC as the Pi's soundcard is mono and not very good.

Promise and volume

---

frontend/src/components/remove-track/__snapshots__/index.spec.js.snap
frontend/src/components/remove-track/index.js
frontend/src/components/remove-track/index.spec.js
frontend/src/components/tracklist/index.js
frontend/src/components/tracklist/index.spec.js

Better remove track functionality

---

backend/src/handlers/mopidy/index.js
backend/src/handlers/mopidy/index.spec.js
backend/src/services/mopidy/index.js
frontend/src/actions/index.js
frontend/src/actions/index.spec.js
frontend/src/containers/dashboard-container/index.spec.js
frontend/src/search/__snapshots__/index.spec.js.snap
mopidy/Dockerfile

The changes needed to make the app work with Mopidy 3.0 and the changes it brought:
https://mopidy.com/blog/2019/12/27/mopidy-3-faq/

Change to work with Mopidy 3.0

---

.env.example
.github/workflows/nodejs.yml
backend/src/decorators/mopidy/track/index.js
backend/src/decorators/mopidy/track/index.spec.js
backend/src/decorators/search/results/__snapshots__/index.spec.js.snap
backend/src/decorators/search/results/index.spec.js
backend/src/services/spotify/index.js
backend/src/services/spotify/index.spec.js
backend/src/utils/recommendations/index.spec.js
docker-compose.yml

FUCK the FUCK the FUCK the FUCK

---

backend/src/app.ts
backend/src/models/setting.ts
backend/src/services/mopidy.ts
backend/src/utils/event-logger.ts
backend/src/utils/scheduler.ts
backend/test/models/setting.test.ts
backend/test/utils/event-logger.test.ts
backend/test/utils/scheduler.test.ts
makefile

Make auto shutdown a bit smarter. It will now:
* Stop playback at 19:00
* Remove all tracks from the playlist that have been played.

Improve auto shutdown

---

frontend/src/components/added-by/__snapshots__/index.spec.js.snap
frontend/src/components/added-by/index.css
frontend/src/components/added-by/index.js
frontend/src/components/current-track/__snapshots__/index.spec.js.snap

https://user-images.githubusercontent.com/4471057/165979915-81386905-d07d-4ac3-b02b-ac271f2e640f.mov

Make AddedBy List Hoverable and Scrollable
